# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\nuser.proto\x12\x04\x61uth"A\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t"\x11\n\x0fUserListRequest"-\n\x10UserListResponse\x12\x19\n\x05users\x18\x01 \x03(\x0b\x32\n.auth.User"\x19\n\x0bUserRequest\x12\n\n\x02id\x18\x01 \x01(\x05"(\n\x0cUserResponse\x12\x18\n\x04user\x18\x01 \x01(\x0b\x32\n.auth.User"-\n\x11\x43reateUserRequest\x12\x18\n\x04user\x18\x01 \x01(\x0b\x32\n.auth.User".\n\x12\x43reateUserResponse\x12\x18\n\x04user\x18\x01 \x01(\x0b\x32\n.auth.User"-\n\x11UpdateUserRequest\x12\x18\n\x04user\x18\x01 \x01(\x0b\x32\n.auth.User".\n\x12UpdateUserResponse\x12\x18\n\x04user\x18\x01 \x01(\x0b\x32\n.auth.User"\x1f\n\x11\x44\x65leteUserRequest\x12\n\n\x02id\x18\x01 \x01(\x05".\n\x12\x44\x65leteUserResponse\x12\x18\n\x04user\x18\x01 \x01(\x0b\x32\n.auth.User2\xc4\x02\n\x05Users\x12>\n\x0bGetUserList\x12\x15.auth.UserListRequest\x1a\x16.auth.UserListResponse"\x00\x12\x32\n\x07GetUser\x12\x11.auth.UserRequest\x1a\x12.auth.UserResponse"\x00\x12\x41\n\nCreateUser\x12\x17.auth.CreateUserRequest\x1a\x18.auth.CreateUserResponse"\x00\x12\x41\n\nUpdateUser\x12\x17.auth.UpdateUserRequest\x1a\x18.auth.UpdateUserResponse"\x00\x12\x41\n\nDeleteUser\x12\x17.auth.DeleteUserRequest\x1a\x18.auth.DeleteUserResponse"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "user_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_USER"]._serialized_start = 20
    _globals["_USER"]._serialized_end = 85
    _globals["_USERLISTREQUEST"]._serialized_start = 87
    _globals["_USERLISTREQUEST"]._serialized_end = 104
    _globals["_USERLISTRESPONSE"]._serialized_start = 106
    _globals["_USERLISTRESPONSE"]._serialized_end = 151
    _globals["_USERREQUEST"]._serialized_start = 153
    _globals["_USERREQUEST"]._serialized_end = 178
    _globals["_USERRESPONSE"]._serialized_start = 180
    _globals["_USERRESPONSE"]._serialized_end = 220
    _globals["_CREATEUSERREQUEST"]._serialized_start = 222
    _globals["_CREATEUSERREQUEST"]._serialized_end = 267
    _globals["_CREATEUSERRESPONSE"]._serialized_start = 269
    _globals["_CREATEUSERRESPONSE"]._serialized_end = 315
    _globals["_UPDATEUSERREQUEST"]._serialized_start = 317
    _globals["_UPDATEUSERREQUEST"]._serialized_end = 362
    _globals["_UPDATEUSERRESPONSE"]._serialized_start = 364
    _globals["_UPDATEUSERRESPONSE"]._serialized_end = 410
    _globals["_DELETEUSERREQUEST"]._serialized_start = 412
    _globals["_DELETEUSERREQUEST"]._serialized_end = 443
    _globals["_DELETEUSERRESPONSE"]._serialized_start = 445
    _globals["_DELETEUSERRESPONSE"]._serialized_end = 491
    _globals["_USERS"]._serialized_start = 494
    _globals["_USERS"]._serialized_end = 818
# @@protoc_insertion_point(module_scope)
